
package WebService1;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Time", targetNamespace = "http://TimeService.mapkn3.my/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Time {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTime", targetNamespace = "http://TimeService.mapkn3.my/", className = "WebService1.GetTime")
    @ResponseWrapper(localName = "getTimeResponse", targetNamespace = "http://TimeService.mapkn3.my/", className = "WebService1.GetTimeResponse")
    @Action(input = "http://TimeService.mapkn3.my/Time/getTimeRequest", output = "http://TimeService.mapkn3.my/Time/getTimeResponse")
    public String getTime();

}
